# Automatically generated by configure - do not modify
TARGET_S390X=y
TARGET_NAME=s390x
TARGET_BASE_ARCH=s390x
TARGET_ABI_DIR=s390x
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /home/unaisp/ssd_sdb1/provm/qemu/qemu-2.8.0/gdb-xml/s390x-core64.xml /home/unaisp/ssd_sdb1/provm/qemu/qemu-2.8.0/gdb-xml/s390-acr.xml /home/unaisp/ssd_sdb1/provm/qemu/qemu-2.8.0/gdb-xml/s390-fpr.xml /home/unaisp/ssd_sdb1/provm/qemu/qemu-2.8.0/gdb-xml/s390-vx.xml /home/unaisp/ssd_sdb1/provm/qemu/qemu-2.8.0/gdb-xml/s390-cr.xml /home/unaisp/ssd_sdb1/provm/qemu/qemu-2.8.0/gdb-xml/s390-virt.xml
CONFIG_I386_DIS=y
CONFIG_S390_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
